<template>
  <div class="shopping-list">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h5>
        <i class="fas fa-shopping-cart me-2"></i>Shopping List
        <small class="text-muted ms-2"
          >(Items: {{ computedShoppingList.ingredients.length }})</small
        >
        <span v-if="computedShoppingList.ingredients.length > 0" class="badge bg-success ms-2">
          Auto-updated
        </span>
      </h5>
      <div>
        <button
          @click="clearAllMeals"
          class="btn btn-outline-danger btn-sm me-2"
        >
          <i class="fas fa-trash"></i> Clear All
        </button>
        <button 
          @click="generateShoppingList" 
          class="btn btn-success btn-sm"
          title="Shopping list updates automatically when you add/remove meals"
        >
          <i class="fas fa-sync"></i> Refresh
        </button>
      </div>
    </div>

    <div class="shopping-items">
      <div
        v-if="computedShoppingList.ingredients.length === 0"
        class="text-muted text-center py-3"
      >
        <i class="fas fa-shopping-cart fa-2x mb-2"></i>
        <p class="mb-1">No ingredients needed</p>
        <small>Add meals to your calendar to automatically generate your shopping list</small>
      </div>
      <div
        v-for="(item, index) in computedShoppingList.ingredients"
        :key="index"
        class="shopping-item"
        :class="{ purchased: item.purchased }"
      >
        <div class="form-check">
          <input
            class="form-check-input"
            type="checkbox"
            :id="`item-${index}`"
            :checked="item.purchased"
            @change="toggleShoppingItem(item.name)"
          />
          <label class="form-check-label" :for="`item-${index}`">
            <span
              class="item-name"
              :class="{
                'text-decoration-line-through text-muted': item.purchased,
              }"
              >{{ item.name }}</span
            >
            <span
              class="item-quantity"
              :class="{
                'text-decoration-line-through text-muted': item.purchased,
              }"
              >{{ item.quantity }}</span
            >
            <span
              v-if="item.sustainable"
              class="sustainable-badge"
              :class="{ 'opacity-50': item.purchased }"
            >
              <i class="fas fa-leaf"></i>
            </span>
          </label>
        </div>
      </div>
    </div>

    <!-- Sustainable Alternatives -->
    <div
      v-if="computedShoppingList.alternatives.length > 0"
      class="sustainable-alternatives mt-3"
    >
      <h6 class="text-success">
        <i class="fas fa-leaf me-1"></i>Sustainable Alternatives
      </h6>
      <div class="alternatives-list">
        <div
          v-for="(alt, index) in computedShoppingList.alternatives"
          :key="index"
          class="alternative-item"
        >
          <div class="alternative-info">
            <strong>{{ alt.original }}</strong> →
            <span class="text-success">{{ alt.alternative }}</span>
          </div>
          <div class="alternative-benefit">{{ alt.benefit }}</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { storeToRefs } from "pinia";
import { useMealStore } from "@/stores/mealStore.js";

// Store
const mealStore = useMealStore();
const { computedShoppingList } = storeToRefs(mealStore);
const { clearAllMeals, toggleShoppingItem } = mealStore;

// Methods
const generateShoppingList = () => {
  // The shopping list is automatically generated by the store
  // This method can be used for manual refresh or additional logic
  // No additional logic needed as shopping list is computed automatically
};
</script>

<style scoped>
.shopping-list {
  background: #ffffff;
  border-radius: 8px;
  padding: 1rem;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  height: calc(50vh - 100px);
  display: flex;
  flex-direction: column;
}

.shopping-items,
.alternatives-list {
  flex: 1;
  overflow-y: auto;
  padding-right: 0.5rem;
}

.shopping-item {
  background: #f8f9fa;
  border: 1px solid #e9ecef;
  border-radius: 6px;
  padding: 0.75rem;
  margin-bottom: 0.5rem;
  transition: all 0.3s ease;
}

.shopping-item:hover {
  border-color: #27ae60;
  background-color: rgba(39, 174, 96, 0.05);
}

.shopping-item.purchased {
  background-color: #e9ecef;
  opacity: 0.7;
  border-color: #dee2e6;
}

.shopping-item .form-check {
  display: flex;
  align-items: center;
  width: 100%;
  margin: 0;
}

.shopping-item .form-check-input {
  margin-right: 0.75rem;
  margin-top: 0;
  transform: scale(1.1);
}

.shopping-item .form-check-label {
  display: flex;
  flex-direction: column;
  width: 100%;
  margin: 0;
  cursor: pointer;
}

.item-name {
  font-weight: 500;
  color: #2c3e50;
  margin-bottom: 0.25rem;
}

.item-quantity {
  color: #6c757d;
  font-size: 0.85rem;
  font-style: italic;
}

.sustainable-badge {
  color: #27ae60;
  font-size: 0.8rem;
}

.text-decoration-line-through {
  text-decoration: line-through !important;
}

.opacity-50 {
  opacity: 0.5 !important;
}

.sustainable-alternatives {
  background: #f8f9fa;
  border-radius: 8px;
  padding: 1rem;
  border-left: 4px solid #27ae60;
}

.alternative-item {
  background: white;
  border-radius: 6px;
  padding: 0.75rem;
  margin-bottom: 0.5rem;
  border: 1px solid #e9ecef;
}

.alternative-info {
  font-size: 0.9rem;
  margin-bottom: 0.25rem;
}

.alternative-benefit {
  font-size: 0.8rem;
  color: #6c757d;
  font-style: italic;
}

.btn-success {
  background: linear-gradient(135deg, #27ae60 0%, #2ecc71 100%);
  border: none;
}

.btn-success:hover {
  background: linear-gradient(135deg, #229954 0%, #27ae60 100%);
  transform: translateY(-1px);
}

.btn-outline-danger:hover {
  transform: translateY(-1px);
}

/* Custom scrollbar */
.shopping-items::-webkit-scrollbar,
.alternatives-list::-webkit-scrollbar {
  width: 6px;
}

.shopping-items::-webkit-scrollbar-track,
.alternatives-list::-webkit-scrollbar-track {
  background: #f1f1f1;
  border-radius: 3px;
}

.shopping-items::-webkit-scrollbar-thumb,
.alternatives-list::-webkit-scrollbar-thumb {
  background: #27ae60;
  border-radius: 3px;
}

.shopping-items::-webkit-scrollbar-thumb:hover,
.alternatives-list::-webkit-scrollbar-thumb:hover {
  background: #229954;
}
</style>
